spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laiqq/springCloudDemo/tree/master/config-repo-center/
          search-paths: config-repo
          username: xx
          password: xx

server:
  port: 1201
