spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laiqq/configRepoCenter/
          search-paths: config-repo
          username: 375113044@qq.com
          password: xxxxx

server:
  port: 1201
